### ISSUE TITLE
Dimensions of jacfun does not match

### ISSUE THREAD

**Issue by calbertsen** [kaskr/RTMB#13]
For a tape with input dimension n and output dimension m, the output of `$jacfun` is an m * n matrix, but the values seems to be in the wrong order. It seems the output should either be an n * m matrix, or the values should be input by row.

For example, with the function
```r
f <- MakeTape(function(x) c(x[1],x[1]+x[2]+3*x[3],x[1]+x[2]+x[3],x[1]*x[2]),numeric(3))
```
I would expect the first column (of the m*n matrix) to be the derivative of the first output w.r.t each of the inputs; c(1,1,1,2) in this case. But the output of
```r
f$jacfun()(c(1,2,3))
```
has c(1,0,0,1).

The output of both
```r
matrix(f$jacfun()(c(1,2,3)),3,4)
```
and
```r
matrix(f$jacfun()(c(1,2,3)),4,3,byrow=TRUE)
```
matches my expectation.

**Comment by kaskr** [comment]
Thanks @calbertsen - You are absolutely right!
`f$jacfun()(1:3)` should be the same as `f$jacobian(1:3)` (which is correctly ordered).
