### ISSUE TITLE
Scoping for use in functions

### ISSUE THREAD

**Issue by James-Thorson-NOAA** [kaskr/RTMB#26]
The existing RTMB examples all seem to involve `MakeADFun` calling function `func` which pulls data from the global environment.  However, in more complicated settings (e.g., packages), the developer might want to provide a wrapper function `fit( data, ...)` that transforms `data` to the format expected  by `func`.  This seems to violate scoping rules, because the transformed copy is not in the global environment.  A simple demo is below.  

What is the intended way to pass objects that are not in the global environment, or am I missing some obvious solution?

Personally, I would prefer an optional argument `data` to `RTMB::MakeADFun` (similar to the argument in `TMB::MakeADFun`), and perhaps some flag that forces RTMB to only look for data in that `data` argument (so that there's no chance of inadvertently pulling data from the global environment without realizing it)

```R
library(RTMB)

nll = function(p){
  getAll(p)
  -1 * sum(dnorm(Y, mean=mu, sd=sd, log=TRUE))
}

run = function(mean=0, sigma=1){
  Y = rnorm(100, mean=0, sd=sigma)
  obj = MakeADFun( func=nll, 
                   parameters = list('mu'=0, 'sd'=1) )
  opt = nlminb( start=obj$par, 
                objective = obj$fn,
                gradient = obj$gr )
  return(opt)
}

# Fails with `Y` generated in a function
out = run()

# Works with `Y` in global environment
Y = rnorm(100)
run()
```

**Comment by phillipbvetter** [comment]
I have previously defined `nll` inside `run`, but didn't think much about it.

A possible solution, although not sure if it's good, is to pass the data as arguments to parameters, and fix them with `map`.

```
library(RTMB)

nll = function(p){
  getAll(p)
  -1 * sum(dnorm(Y, mean=mu, sd=sd, log=TRUE))
}

run = function(mean=0, sigma=1){
  Y = rnorm(100, mean=0, sd=sigma)
  Y.factor = factor(rep(NA,length(Y))) 
  
  obj = MakeADFun(func=nll, 
                  parameters = list('mu'=0, 'sd'=1, Y=Y),
                  map=list(Y=Y.factor)
  )
  
  opt = nlminb( start=obj$par, 
                objective = obj$fn,
                gradient = obj$gr )
  return(opt)
}

out = run()
```

**Comment by James-Thorson-NOAA** [comment]
Thanks for the feedback! 

I'm not confident that passing it via `parameters` would deal well with discrete-valued data.  

Regarding defining `nll` within `run` (in this example) ... I'll try that now!  However, I'd prefer to keep `nll` separate (so that is is publicly available as an exported function), so that it is available for other uses without requiring a duplicate definition.

**Comment by kaskr** [comment]
> What is the intended way to pass objects that are not in the global environment, or am I missing some obvious solution?

The intended way is to use environments, e.g. :

```
run = function(mean=0, sigma=1){
  environment(nll) <- environment()
}
```

An example using this approach from a package is here: https://github.com/kaskr/RTMB/tree/master/rtmbTest .
But this is just on way to do it. An alternative could be to generate `nll` from a function taking `data` as input. That would automatically attach the right environment to `nll`.

**Comment by James-Thorson-NOAA** [comment]
Great.  Yes, using `environment()` works as you hos in that `rtmbTest` demo.  I'll go with that option for now.
