### ISSUE TITLE
Guidance on cholesky decomposition

### ISSUE THREAD

**Issue by Cole-Monnahan-NOAA** [kaskr/RTMB#29]
I'm trying to recreate a model from Stan that uses a quadratic exponential covariance form for a spatial model (Stan code [here](https://github.com/stan-dev/posteriordb/blob/master/posterior_database/models/stan/gp_pois_regr.stan)). Once the covariance matrix is built they take the cholesky decomposition of it.

When I try this in RTMB it complains about the matrix being complex. I know it's not but presume this is because RTMB uses complex numbers on the backend. Is there an easy way around this, or an alternative approach?

**Comment by kaskr** [comment]
`chol` is now added to RTMB
