### ISSUE TITLE
Strange behaviour with sapply

### ISSUE THREAD

**Issue by paul-vdb** [kaskr/RTMB#35]
Recent ish update to RTMB has broken some of my existing code due to a change with `sapply`.  Specifically, to have RTMB functions run as custom distributions within Nimble.

Here is a simple reproducible example that does not work when RTMB is loaded (runs fine otherwise) that is causing the more cryptic error in Nimble.

```
library(RTMB)
sapply(list(), \(x, i) x[i], 1)
```

Thanks,
Paul

**Comment by kaskr** [comment]
I think `RTMB::sapply` was always like that, i.e. didn't work in this edge case.

**Comment by paul-vdb** [comment]
Thanks. This has resolved the issue with Nimble.
