### ISSUE TITLE
`solve(sparseMatrix, vec)` implementation?

### ISSUE THREAD

**Issue by James-Thorson-NOAA** [kaskr/RTMB#37]
I'm trying to compare a "state-space" and "innovations" parameterization for a multivariate space-time model with diffusive movement over time.  The state-space option is easy using the `AD` coerce function as provided previously:

```R
Q = t(L) %*% inverseD %*% L
dgmrf( eps, mu=0, Q=Q, log=TRUE )
```

However, I'm hoping that it might be faster to do the innovations version directly:

```R
dgmrf( eps0, mu=0, Q=inverseD, log=TRUE )
eps = solve( L, eps0 )
```

However, during `MakeADFun` I get the informative error:

```R
Error in .local(a, b, ...) : Sparse AD solve is not yet implemented
```

Is this a large lift, or any way I can help?

**Comment by kaskr** [comment]
@James-Thorson-NOAA It's the intention that the AD solve should select appropriate methods depending on the detected sparsity structure. The triangular case is particularly easy and could be implemented as a first step.

**Comment by James-Thorson-NOAA** [comment]
OK, no hurry on my account, I can test it in TMB.  In the case I'm exploring, L is sparse-asymmetric-nontriangular (sorry for the confusion with a lower-triangle matrix), so it's probably not the first case covered.

Closing for now, but feel free to update here if this feature gets added.
