### ISSUE TITLE
Can't compile TMB object for usage with RTMB on x64 Windows

### ISSUE THREAD

**Issue by jgbabyn** [kaskr/RTMB#39]
I'm not sure if this is more a TMB issue or an RTMB issue or maybe even an Rtools issue, but trying to compile even a very simple TMB template (shown at the bottom) to interface with RTMB results in the following error with the suggested compile settings `framework='TMBad',openmp=FALSE,flags='-DTMBAD_INDEX_TYPE=uint64_t` on x64 Windows 11 with R 4.4.1 and the corresponding Rtools:

```
`using C++ compiler: 'G__~1.EXE (GCC) 13.2.0'
g++ -std=gnu++17  -I"c:/PROGRA~1/R/R-44~1.1/include" -DNDEBUG -I"C:/Users/jonba/AppData/Local/R/WIN-LI~1/4.4/TMB/include" -I"C:/Users/jonba/AppData/Local/R/WIN-LI~1/4.4/RCPPEI~1/include"  -DTMB_SAFEBOUNDS -DTMB_EIGEN_DISABLE_WARNINGS -DLIB_UNLOAD=R_unload_basictmbtape  -DTMB_LIB_INIT=R_init_basictmbtape  -DTMBAD_FRAMEWORK    -I"C:/rtools44/x86_64-w64-mingw32.static.posix/include"     -DTMBAD_INDEX_TYPE=uint64_t -c basictmbtape.cpp -o basictmbtape.o
as: basictmbtape.o: too many sections (91106)
C:\Users\jonba\AppData\Local\Temp\ccEQfksg.s: Assembler messages:
C:\Users\jonba\AppData\Local\Temp\ccEQfksg.s: Fatal error: can't write 21 bytes to section .text of basictmbtape.o: 'file too big'
as: basictmbtape.o: too many sections (91106)
C:\Users\jonba\AppData\Local\Temp\ccEQfksg.s: Fatal error: basictmbtape.o: file too big
make: *** [c:/PROGRA~1/R/R-44~1.1/etc/x64/Makeconf:296: basictmbtape.o] Error 1
Error in TMB::compile("basictmbtape.cpp", framework = "TMBad", openmp = FALSE,  : 
  Compilation failed`
```

The same example works as expected on x64 Ubuntu 24.04 with GCC and on ARM Windows 11 (where Rtools uses clang). And it compiles fine with the default flags but then it of course doesn't interface with RTMB. Is there perhaps some extra flag required to get this working on Windows x64 that's just not documented?

**basictmbtape.cpp**

```cpp
#include <TMB.hpp>
template<class Type>
Type objective_function<Type>::operator() ()
{

  PARAMETER(x);

  Type ret = x*x;
  return ret;
}
```

**basicexample.R**

```r
library(TMB)
library(RTMB)
TMB::compile("basictmbtape.cpp",framework="TMBad",openmp=FALSE,flags="-DTMBAD_INDEX_TYPE=uint64_t")
dyn.load(dynlib("basictmbtape"))

parm = list(x=2)
data = list()
obj = TMB::MakeADFun(data,parameters = parm,DLL="basictmbtape")

tmbtape = GetTape(obj)

fn = function(x){
    xx = x$x
    tmbtape(c(xx))
}

parms = list()
parms$x = -50

obj = MakeADFun(fn,parms)
obj$fn()
obj$gr()
```

**Comment by kaskr** [comment]
The problem is that `flags` is used for *compiler flags* not *pre-processor flags*. So, when setting `flags="-DTMBAD_INDEX_TYPE=uint64_t"`  it implicitly removes the compiler optimization, and other essential platform specific flags!
It might work to use `CPPFLAGS=...`, but I think the safest is to hard code the variables in the cpp template, right before including `TMB.hpp`:

```cpp
#undef CPPAD_FRAMEWORK
#define TMBAD_FRAMEWORK
#define TMBAD_INDEX_TYPE uint64_t

#include <TMB.hpp>
template<class Type>
Type objective_function<Type>::operator() ()
{

  PARAMETER(x);

  Type ret = x*x;
  return ret;
}
```
 and then compile with

```r
TMB::compile("basictmbtape.cpp",openmp=FALSE)
```

**Comment by jgbabyn** [comment]
Ahh okay! Thanks, this works. It wasn't clear to me that `flags` is only compiler flags especially as it worked on other platforms.

Thanks again for the help, much appreciated!
